ARG BASE
ARG TRUSTEE_ATTESTER=quay.io/trusted-execution-clusters/trustee-attester:TPM-additional-dev
ARG CLEVIS_PIN_TRUSTEE=quay.io/trusted-execution-clusters/clevis-pin-trustee
ARG IGNITION=quay.io/trusted-execution-clusters/ignition:attestation
FROM $TRUSTEE_ATTESTER as kbc
FROM $CLEVIS_PIN_TRUSTEE as clevis
FROM $IGNITION as ignition

FROM $BASE

COPY ./usr /usr
COPY --from=kbc /usr/local/bin/trustee-attester /usr/bin/trustee-attester
COPY --from=clevis /usr/bin/clevis-pin-trustee /usr/bin/clevis-pin-trustee
COPY --from=clevis /usr/bin/clevis-encrypt-trustee /usr/bin/clevis-encrypt-trustee
COPY --from=clevis /usr/bin/clevis-decrypt-trustee /usr/bin/clevis-decrypt-trustee
COPY --from=ignition /usr/bin/ignition /usr/lib/dracut/modules.d/30ignition/ignition

RUN set -xeuo pipefail && \
    KERNEL_VERSION="$(basename $(ls -d /lib/modules/*))" && \
    raw_args="$(lsinitrd /lib/modules/${KERNEL_VERSION}/initramfs.img | grep '^Arguments: ' | sed 's/^Arguments: //')" && \
    stock_arguments=$(echo "$raw_args" | sed "s/'//g") && \
    echo "Using kernel: $KERNEL_VERSION" && \
    echo "Dracut arguments: $stock_arguments" && \
    mkdir -p /tmp/dracut /var/roothome && \
    dracut $stock_arguments && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" && \
    bootc container lint

ARG COM_COREOS_OSNAME
LABEL com.coreos.osname=$COM_COREOS_OSNAME
